// Generated by tools/design_system_tokens.py from design-system/tokens.json. Do not edit.
import SwiftUI

enum SignalTokens {
    static let canvas = Color(red: 11 / 255, green: 16 / 255, blue: 15 / 255)
    static let surface = Color(red: 20 / 255, green: 28 / 255, blue: 25 / 255)
    static let raised = Color(red: 27 / 255, green: 38 / 255, blue: 33 / 255)
    static let well = Color(red: 14 / 255, green: 21 / 255, blue: 18 / 255)
    static let text = Color(red: 237 / 255, green: 243 / 255, blue: 238 / 255)
    static let muted = Color(red: 162 / 255, green: 178 / 255, blue: 167 / 255)
    static let accent = Color(red: 155 / 255, green: 232 / 255, blue: 168 / 255)
    static let accentInk = Color(red: 11 / 255, green: 33 / 255, blue: 18 / 255)
    static let line = Color(red: 60 / 255, green: 81 / 255, blue: 69 / 255)
    static let control = Color(red: 107 / 255, green: 133 / 255, blue: 115 / 255)
    static let attention = Color(red: 242 / 255, green: 192 / 255, blue: 120 / 255)
    static let danger = Color(red: 255 / 255, green: 152 / 255, blue: 152 / 255)

    enum Spacing {
        static let xs: CGFloat = 4
        static let sm: CGFloat = 8
        static let md: CGFloat = 12
        static let lg: CGFloat = 16
        static let xl: CGFloat = 24
        static let xxl: CGFloat = 32
    }

    enum Radii {
        static let control: CGFloat = 6
        static let card: CGFloat = 10
    }

    enum Typography {
        static let desktopBody: CGFloat = 14
        static let phoneBody: CGFloat = 17
        static let desktopMeta: CGFloat = 12
        static let phoneMeta: CGFloat = 13
    }

    enum Size {
        static let desktopControl: CGFloat = 36
        static let phoneControl: CGFloat = 48
        static let phoneTarget: CGFloat = 44
    }
}
