#!/usr/bin/env python3
"""Validate and generate Signal tokens for Swift and the bundled workshop."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "design-system/tokens.json"
OUTPUTS = (
    ROOT / "panel/Sources/BobPanel/SignalTokens.generated.swift",
    ROOT / "ios/BobPhone/SignalTokens.generated.swift",
)
WEB = ROOT / "design-system/workshop"
COLORS = (
    "canvas", "surface", "raised", "well", "text", "muted", "accent",
    "accentInk", "line", "control", "attention", "danger",
)
NUMBERS = {
    "spacing": ("xs", "sm", "md", "lg", "xl", "xxl"),
    "radii": ("control", "card"),
    "type": ("desktopBody", "phoneBody", "desktopMeta", "phoneMeta"),
    "size": ("desktopControl", "phoneControl", "phoneTarget"),
}
TEXT_PAIRS = (
    ("text", "canvas"), ("text", "surface"), ("text", "raised"),
    ("muted", "canvas"), ("muted", "surface"), ("muted", "raised"),
    ("accent", "canvas"), ("accent", "raised"),
    ("attention", "surface"), ("attention", "raised"),
    ("danger", "surface"), ("danger", "raised"),
    ("accentInk", "accent"),
)
#: A divider is not text, but it must still read as a line: 2:1 on the two
#: grounds a rule is drawn on, and the only edge an unfilled chip has.
LINE_PAIRS = (("line", "canvas"), ("line", "surface"))
LINE_FLOOR = 2.0


def contrast(a: str, b: str) -> float:
    def luminance(color: str) -> float:
        channels = [int(color[i:i + 2], 16) / 255 for i in (1, 3, 5)]
        linear = [c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
                  for c in channels]
        return sum(weight * channel for weight, channel in
                   zip((0.2126, 0.7152, 0.0722), linear))
    hi, lo = sorted((luminance(a), luminance(b)), reverse=True)
    return (hi + 0.05) / (lo + 0.05)


def validate(value: object) -> dict:
    if not isinstance(value, dict) or set(value) != {"name", "version", "colors", *NUMBERS}:
        raise ValueError("unexpected token sections")
    if value["name"] != "Signal" or value["version"] != 1:
        raise ValueError("unsupported token version")
    colors = value["colors"]
    if not isinstance(colors, dict) or set(colors) != set(COLORS):
        raise ValueError("unexpected colors")
    if any(not isinstance(colors[k], str) or not re.fullmatch(r"#[0-9A-Fa-f]{6}", colors[k]) for k in COLORS):
        raise ValueError("colors must be six-digit hex")
    for foreground, background in TEXT_PAIRS:
        if contrast(colors[foreground], colors[background]) < 4.5:
            raise ValueError(f"insufficient contrast: {foreground} on {background}")
    for foreground, background in LINE_PAIRS:
        if contrast(colors[foreground], colors[background]) < LINE_FLOOR:
            raise ValueError(f"divider too faint: {foreground} on {background}")
    for section, names in NUMBERS.items():
        items = value[section]
        if not isinstance(items, dict) or set(items) != set(names):
            raise ValueError(f"unexpected {section} tokens")
        if any(type(items[k]) is not int or not 0 < items[k] <= 80 for k in names):
            raise ValueError(f"invalid {section} size")
    if value["size"]["phoneTarget"] < 44 or value["size"]["phoneControl"] < 44:
        raise ValueError("phone controls need at least 44 points")
    return value


def swift(value: dict) -> str:
    lines = [
        "// Generated by tools/design_system_tokens.py from design-system/tokens.json. Do not edit.",
        "import SwiftUI", "", "enum SignalTokens {",
    ]
    for name in COLORS:
        code = value["colors"][name].lstrip("#")
        rgb = [int(code[i:i + 2], 16) for i in (0, 2, 4)]
        lines.append(f"    static let {name} = Color(red: {rgb[0]} / 255, green: {rgb[1]} / 255, blue: {rgb[2]} / 255)")
    for section, names in NUMBERS.items():
        lines.append("")
        swift_section = "Typography" if section == "type" else section.capitalize()
        lines.append(f"    enum {swift_section} {{")
        for name in names:
            lines.append(f"        static let {name}: CGFloat = {value[section][name]}")
        lines.append("    }")
    lines += ["}", ""]
    return "\n".join(lines)


def generated(value: dict) -> dict[Path, str]:
    canonical = json.dumps(value, indent=2, ensure_ascii=False) + "\n"
    css = ["/* Generated by tools/design_system_tokens.py. Do not edit. */", ":root {"]
    css += [f"  --signal-{k}: {value['colors'][k]};" for k in COLORS]
    for section, names in NUMBERS.items():
        css += [f"  --signal-{section}-{name}: {value[section][name]}px;" for name in names]
    css += ["}", ""]
    js = "// Generated by tools/design_system_tokens.py. Do not edit.\nwindow.SignalDefaults = " + json.dumps(value, sort_keys=True, separators=(",", ":")) + ";\n"
    files = {
        OUTPUTS[0]: swift(value), OUTPUTS[1]: swift(value),
        WEB / "tokens.json": canonical,
        WEB / "tokens.css": "\n".join(css),
        WEB / "tokens.js": js,
    }
    for name in ("index.html", "workshop.css", "workshop.js", "tokens.json", "tokens.css", "tokens.js"):
        content = files.get(WEB / name)
        if content is None:
            content = (WEB / name).read_text()
        files[ROOT / "panel/Sources/BobPanel/Resources/workshop" / name] = content
        files[ROOT / "ios/BobPhone/Resources/workshop" / name] = content
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated outputs differ")
    args = parser.parse_args()
    source = validate(json.loads(SOURCE.read_text()))
    stale = []
    for path, content in generated(source).items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        parser.exit(1, "stale generated tokens: " + ", ".join(stale) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
